const response = {
  data: "ACCESS_NUMBER:456198104:61489929189",
  status: 200,
  statusText: "OK",
  headers: {
    "access-control-allow-origin": "*",
    "cf-cache-status": "DYNAMIC",
    "cf-ray": "7e2d929a2d983187-BOM",
    connection: "close",
    "content-encoding": "br",
    "content-type": "text/html; charset=UTF-8",
    date: "Fri, 07 Jul 2023 05:08:58 GMT",
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    "referrer-policy": "same-origin",
    "report-to":
      '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=NK%2BGuC2cZbxraZ38Tx7u2RJJnOP56XoZ5OFRsDKPZ%2FYeSi4BBt31%2FIDZHMvzdQOYi2OleAgCFPDBjbHHwCj1tiMfHklKi9Ifa1qF4WdP1qdpPwEEXG9Aoov5%2F08%3D"}],"group":"cf-nel","max_age":604800}',
    server: "cloudflare",
    "strict-transport-security": "max-age=31536000;",
    "transfer-encoding": "chunked",
    "x-content-type-options": "nosniff",
    "x-xss-protection": "1; mode=block",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    method: "get",
    url: "/stubs/handler_api.php?api_key=149056Ua7dafdd645b8625d5159982d88beea23&action=getNumber&service=dh&operator=any&service=dh&country=175",
  },
  request: {
    requestMethod: "GET",
  },
};

const response2 = {
  data: "ACCESS_NUMBER:456209484:79966818793",
  status: 200,
  statusText: "OK",
  headers: {
    "access-control-allow-origin": "*",
    "cf-cache-status": "DYNAMIC",
    "cf-ray": "7e2de9884b2585a5-BOM",
    connection: "close",
    "content-encoding": "br",
    "content-type": "text/html; charset=UTF-8",
    date: "Fri, 07 Jul 2023 06:08:19 GMT",
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    "referrer-policy": "same-origin",
    "report-to":
      '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=MSueSA3XQnQZr0%2Bl1cD9OeEPIDA6puu491OctK9j%2F3TH66fMIlNzr0GiJIX0K09w0F6uWEHxYG6W6GqU%2BcdOkuDZ%2Fse3AoJ0zOZgRyGjYyoj8ig5Fx3TeChcGWQ%3D"}],"group":"cf-nel","max_age":604800}',
    server: "cloudflare",
    "strict-transport-security": "max-age=31536000;",
    "transfer-encoding": "chunked",
    "x-content-type-options": "nosniff",
    "x-xss-protection": "1; mode=block",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    method: "get",
    url: "/stubs/handler_api.php?api_key=149056Ua7dafdd645b8625d5159982d88beea23&action=getNumber&service=fb&operator=any&service=fb&country=0",
  },
  request: {
    requestMethod: "GET",
  },
};
